server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://localhost:33066/todo_app?characterEncoding=utf8&character_set_server=utf8mb4&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
  application:
    name: todo-app
mybatis:
  mapper-locations: classpath:mapper/*.xml
